# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/configuration/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys

# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default

MARKDOWN_MARKDOWNLINT_CONFIG_FILE: .markdown-lint.yml
GHERKIN_GHERKIN_LINT_CONFIG_FILE: .gherkin-lintrc

ENABLE_LINTERS:
  - BASH_EXEC
  - BASH_SHELLCHECK
  - BASH_SHFMT
  - JAVASCRIPT_ES
  - JSON_JSONLINT
  - JSON_NPM_PACKAGE_JSON_LINT
  - MARKDOWN_MARKDOWNLINT
  - XML_XMLLINT
  - YAML_YAMLLINT
  - DOCKERFILE_HADOLINT
  - GHERKIN_GHERKIN_LINT
  - OPENAPI_SPECTRAL

DISABLE:
  - COPYPASTE # Comment to enable checks of excessive copy-pastes
  # - SPELL # Uncomment to disable checks of spelling mistakes
SHOW_ELAPSED_TIME: false
FILEIO_REPORTER: false
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
FILTER_REGEX_EXCLUDE: (.github/|tools/)
